PROJECT_ID: casablanca-dev-project
BUCKET_NAME: casablanca-datasets

data_filepath: data/files_mapping_all.tsv
metadata_filepath: data/ids_metadata.json

train_ratio: 0.7

packages:
  - lpips

max_utterances_pre_id: 10

dataset_settings:
  more_frames:
    train_size: 14000
    test_size: 6000
    frames_indices:
      - 60
      - 80
  base:
    train_size: 7000
    test_size: 3000
    frames_indices:
      - 80
  more_vid:
    train_size: 14000
    test_size: 6000
    frames_indices:
      - 80

frame_separator: frame
dataset_creation:
  unique_ids: 20
  n_videos_per_id: 5
  n_clips_per_video: 1
  frames:
    initial: 0
    final: 80
    step: 40
  ids:
  - id00012
  - id00015
  - id00016
  - id00028
  - id00060
  - id00103
  - id00116
  - id00117
  - id00126
  - id00127
  - id00181
  - id00098
  - id00099
  - id00100
  - id00104
  - id00105
  - id00109
  - id00111
  - id00114
  - id00180
#  - id00070
#  - id00071
#  - id00090
#  - id00091
#  - id00137
#  - id00138