PROJECT_ID: casablanca-dev-project
BUCKET_NAME: casablanca-datasets

data_filepath: data/files_mapping.tsv


train_ratio: 0.7

packages:
  - lpips

max_utterances_pre_id: 10

frame_separator: "frame"
dataset_creation:
  unique_ids: 20
  n_videos_per_id: 2
  n_clips_per_video: 1
  frames:
    initial: 10
    final: 100
    step: 20
  ids:
  - id00012
  - id00015
#  - id00016
#  - id00028
#  - id00060
#  - id00103
#  - id00116
#  - id00117
#  - id00126
#  - id00127
#  - id00181
#  - id00098
#  - id00099
#  - id00100
#  - id00104
#  - id00105
#  - id00109
#  - id00111
#  - id00114
#  - id00180